name: cross-browser-e2e
on: [push]
jobs:
  ie:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.x'
      - run: bundle install
      - run: bundle exec rspec
        env:
          BROWSER: ie
  safari:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.x'
      - run: |
          brew tap homebrew/cask-versions
          brew cask install safari-technology-preview
          sudo /Applications/Safari\ Technology\ Preview.app/Contents/MacOS/safaridriver --enable
          /Applications/Safari\ Technology\ Preview.app/Contents/MacOS/safaridriver -p 0 &
      - run: bundle install
      - run: bundle exec rspec
        env:
          BROWSER: safari
  firefox:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.x'
      - run: bundle install
      - run: bundle exec rspec
        env:
          BROWSER: firefox
  # Chromium base Edge Supported selenium v4
  # edge:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-ruby@v1
  #       with:
  #         ruby-version: '2.6.x'
  #     - run: bundle install
  #     - run: bundle exec rspec
  #       env:
  #         BROWSER: edge
  chrome:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.x'
      - run: bundle install
      - run: bundle exec rspec
        env:
          BROWSER: chrome
